### ISSUE TITLE
"Fossasia" logo should be made static

### ISSUE THREAD

**Issue by SilentFlame** [fossasia/fossasia.org#32]
As seen at the top right corner the `fossasia` is clearly and well visible.
![pic1](https://cloud.githubusercontent.com/assets/9693795/13557489/641a5f26-e417-11e5-8e05-3c44c476d8fb.png)
**Problem** :Now when I opened the side bar on left the `fossasia` shifts to place where it's not completely visible.
![pic2](https://cloud.githubusercontent.com/assets/9693795/13557490/67e55a84-e417-11e5-9de2-497df2432b52.png)

I think we should either make the entire upper bar static or just make the `fossasia` part static.

**Comment by ashutoshsaboo** [comment]
Hi @SilentFlame . I don't know why it's getting viewed like that on your Firefox. But on my Chrome (on Ubuntu) , it seems to be completely fine. And there's no need of keeping the `FossAsia` logo static, because in the right slider the logo is also present, and the original logo on the web page, gets completely hidden, so I guess that's completely consistent and fair. And also, that if we keep any of the top nav bar or the logo static, it would look really bad. That's the reason. 

I am attaching these screenshots jut for your reference-:

(Without the right slider open)-:

![selection_005](https://cloud.githubusercontent.com/assets/9900945/13627497/bdab3648-e5f0-11e5-8152-88a566ceeb54.png)

(With the right slider open)-:

![selection_004](https://cloud.githubusercontent.com/assets/9900945/13627519/e7c4e4ec-e5f0-11e5-870a-f9df8c5c11a9.png)

So, I guess the existing design is fair and consistent. Hence, the issue must be closed. 

@jig08 Your views on this. Thanks! :smile:

**Comment by SilentFlame** [comment]
@ashutoshsaboo you hadn't made the screenshot properly.
Either too much zoom or else you are making a partial shot.
check once again I suggest because It is what it's visible above in the screenshots above I provided. 
and I can clearly see that your shot is also having th esame p[roblem just the thing is didn't show that in shot coz of %of zoom.
so try zooming out to 100% or I'll say `ctrl+0` as you suggest for 100% zoom. :wink:
