### ISSUE TITLE
Add name of app below each screenshot of the Android apps

### ISSUE THREAD

**Issue by mariobehling** [fossasia/fossasia.org#398]
What style can we implement to show the name below the Android apps that looks good?

**Comment by siddharthgusain** [comment]
Can we add logos below screenshots ?and add the links to these logos instead of screenshots?
 or A div with simply the name of app with red background ?

**Comment by kksinghal** [comment]
I think that the name and the sub-type should be added on the right side of each app image . Because this is my screen . 
![image](https://user-images.githubusercontent.com/26023139/49199450-e3bd4280-f3bd-11e8-8d60-b1f27165ff58.png)
If I add the name at the bottom , it will almost be overflowing our viewport height . 
For Example - 
## SUSI.Ai
 Personal Assistant

@mariobehling
