### ISSUE TITLE
 homepage of fossasia.org in dropdown menu navigator please add scroll bar or make all the option  visible in desktop version

### ISSUE THREAD

**Issue by vikramroy622** [fossasia/fossasia.org#766]
homepage of fossasia.org in dropdown menu navigator please add scroll bar or make all the option visible  till the end
![WhatsApp Image 2020-08-13 at 1 38 06 PM (1)](https://user-images.githubusercontent.com/64978616/90114253-1795f280-dd70-11ea-92d3-839f3183e2de.jpeg)

![WhatsApp Image 2020-08-13 at 1 38 06 PM](https://user-images.githubusercontent.com/64978616/90114334-33999400-dd70-11ea-9986-9a99c0fef2e7.jpeg)
here in both menu not shows all the option

**Comment by shantanumallik** [comment]
**I am working on this issue**

This issue is prevalent in the mobile version of the website as well. This is how it looks on an iPhone X.

Unable to scroll beyond the project ***Scrum Helper*.**

![FOSSASIA_ISSUE_1](https://user-images.githubusercontent.com/63910430/90536391-a1432700-e199-11ea-9be8-61124e94db72.png)

**Comment by vikramroy622** [comment]
Good ! keep it up and all the best.

**Comment by vatsal-M** [comment]
My team would like to work on this issue. Is it available?

**Comment by shantanumallik** [comment]
@vatsal-M I am working on it already.

**Comment by shantanumallik** [comment]
@vikramroy622  Created a PR #771 for this issue.

Live Demo: https://shantanumallik.github.io/fossasia.org/

**Comment by mariobehling** [comment]
We will redesign the site at one point and resolve this then.
