### ISSUE TITLE
UI-UX Updations

### ISSUE THREAD

**Issue by Shivang-Bhandari** [fossasia/fossasia.org#82]
@mariobehling sir i would like to work on making the overall UI-UX better for the website. There are a lot of places where the Website can be made more interactive and more user friendly.
I have a few changes in mind and will start working on them as soon as i get a confirmation.

**Comment by mariobehling** [comment]
Hi @Shivang-Bhandari, thanks for your enthusiasm. For the moment we would like to focus on our software projects rather than on the website. A change of the website would in any case demand a lot of coordination and currently there are software projects that are about to release. 

Regarding this issue "UI Updates" is not a specific issue. Therefore I am closing this. It would be great, if you could help with the Open Event project for example. Cheers.
